### ISSUE TITLE
api_call() returns false on "unknown" https certificate

### ISSUE THREAD

**Issue by chris2286266** [matveyco/cex.io-api-php#9]
As a lot of PHP distributions don't have certificate handling (and so no keychain to verify the server certificate of https://cex.io/api), the call curl_exec($ch) in function post returns false.
To switch off certificate validation use "curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);" in function post.
Maybe this should be configurable?

**Comment by birjj** [comment]
This would lower the security, which is not a good idea for a platform such as CEX. In addition, it doesn't solve the underlying issue, but simply stops curl from reporting it.

A better option is to fix the issue by having users download an updated .pem file (such as [this](http://curl.haxx.se/ca/cacert.pem)) and add it to their php.ini. I submitted a pull request with this info added to the readme.

**Comment by matveyco** [comment]
Check out latest fixes.
